### ISSUE TITLE
Generalise visualisation to Canada level

### ISSUE THREAD

**Issue by janoschortmann** [nickbent/covid-quebec-ontario#6]
Add a possibility to select Canada-wide or a province.

1. If Canada selected, show curve for all of Canada, show map of Canada with current figures per province (as a heatmap)
2. If a province is selected, show the curve for that province and a map of that province with current figures per region (as a heatmap)
3. Option to select “normalise by population”  to show the heatmap as cases per population

**Comment by nickbent** [comment]
I think we should also add : tests /100k, this will give an idea of what provinces are testing the most and some sort of positives/test. This will give better information about why there might be differences in positive rates in some provinces

**Comment by nickbent** [comment]
merge this with https://github.com/nickbent/covid-quebec-ontario/issues/3
